version: "3.3"

services:
  myaccount_mongo:
    image: mongo
    restart: always
    networks:
      - private_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  myaccount_app:
    build:
      context: .
    restart: always
    depends_on:
      - myaccount_mongo
    networks:
      - private_network
    ports:
      - '${PORT:-8080}:8080'
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      MONGODB_URL: mongodb://root:example@myaccount_mongo:27017/
      FIREFLY_III_URL: ${FIREFLY_III_URL}
      FIREFLY_III_CLIENT_ID: ${FIREFLY_III_CLIENT_ID}
      FIREFLY_III_CLIENT_SECRET: ${FIREFLY_III_CLIENT_SECRET}


networks:
  private_network:

volumes:
  mongo_data: